---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен быть доступен на различных устройствах.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика..
implicit:
  - Должна соблюдаться конфиденциальность данных пользователей.
  - Интерфейс должен быть интуитивно-понятным и легким в использовании.
  - Должна быть определенная производительность и быстрый ответ при выполнении действий.
  - Сайт должен поддерживать различные языки и культурные особенности.
  - Необходима оперативная поддержка и обслуживание системы.
